/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex.schema.raw('TRUNCATE faculty CASCADE');
  await knex('faculty').del()
  await knex('faculty').insert([
    {id: 1, rank: 'Capt', first: 'a', last: 'oem1', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 2, rank: 'Capt', first: 'a', last: 'oem2', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 3, rank: 'Capt', first: 'a', last: 'oem3', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 4, rank: 'TSgt', first: 'a', last: 'oem4', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 5, rank: 'TSgt', first: 'a', last: 'oem5', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 6, rank: 'TSgt', first: 'a', last: 'oem6', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 7, rank: 'Capt', first: 'a', last: 'sbm1', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 8, rank: 'Capt', first: 'a', last: 'sbm2', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 9, rank: 'Capt', first: 'a', last: 'sbm3', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 10, rank: 'TSgt', first: 'a', last: 'sbm4', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 11, rank: 'TSgt', first: 'a', last: 'sbm5', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 12, rank: 'TSgt', first: 'a', last: 'sbm6', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 13,  rank: 'Civ', first: 'a', last: 'sbm7', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 14, rank: 'Capt', first: 'a', last: 'sew1', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 15, rank: 'Capt', first: 'a', last: 'sew2', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 16, rank: 'Capt', first: 'a', last: 'sew3', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 17, rank: 'TSgt', first: 'a', last: 'sew4', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 18, rank: 'TSgt', first: 'a', last: 'sew5', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 19, rank: 'TSgt', first: 'a', last: 'sew6', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 20, rank: 'Capt', first: 'a', last: 'fun1', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 21, rank: 'TSgt', first: 'a', last: 'fun2', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 22, rank: 'TSgt', first: 'a', last: 'fun3', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 23, rank: 'TSgt', first: 'a', last: 'fun4', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 24,  rank: 'Civ', first: 'a', last: 'fun5', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 25,  rank: 'Civ', first: 'a', last: 'fun6', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 26, rank: 'Capt', first: 'a', last: 'int1', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 27, rank: 'Capt', first: 'a', last: 'int2', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 28, rank: 'TSgt', first: 'a', last: 'int3', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 29, rank: 'TSgt', first: 'a', last: 'int4', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 30,  rank: 'Civ', first: 'a', last: 'int5', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 31,  rank: 'Civ', first: 'a', last: 'int6', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 32,  rank: 'Civ', first: 'a', last: 'int7', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 33,  rank: 'Civ', first: 'a', last: 'int8', nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 34, rank: 'Capt', first: 'a', last: '',     nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 35, rank: 'Capt', first: 'a', last: '',     nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 36, rank: 'Capt', first: 'a', last: '',     nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 37, rank: 'TSgt', first: 'a', last: '',     nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 38, rank: 'TSgt', first: 'a', last: '',     nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''},
    {id: 39, rank: 'TSgt', first: 'a', last: '',     nickname: '', email: 'i@sf.mil', phone_work: '', phone_cell: ''}
  ]);

  await knex.raw('SELECT SETVAL(pg_get_serial_sequence(\'faculty\',\'id\'), (SELECT MAX(id) FROM faculty) )');

  await knex.schema.raw('TRUNCATE TABLE room CASCADE');
  await knex('room').del()
  await knex('room').insert([
    {id: 1,  bldg: '8175', room: 'Orange', phone: '', capacity: 24},
    {id: 2,  bldg: '8175', room: 'Yellow', phone: '', capacity: 24},
    {id: 3,  bldg: '8175', room: 'Red',    phone: '', capacity: 24},
    {id: 4,  bldg: '8175', room: 'Green',  phone: '', capacity: 24},
    {id: 5,  bldg: '8175', room: '164',    phone: '', capacity: 12},
    {id: 6,  bldg: '8175', room: '165',    phone: '', capacity: 12},
    {id: 7,  bldg: '8175', room: '159',    phone: '', capacity: 12},
    {id: 8,  bldg: '8175', room: '161',    phone: '', capacity: 12},
    {id: 9,  bldg: '8175', room: '155',    phone: '', capacity: 12},
    {id: 10, bldg: '8175', room: '156',    phone: '', capacity: 12},
    {id: 11, bldg: '8175', room: '113',    phone: '', capacity: 24},
    {id: 12, bldg: '8175', room: '119',    phone: '', capacity: 24},
    {id: 13, bldg: '8175', room: '119b',   phone: '', capacity: 24},
    {id: 14, bldg: '8173', room: '121a',   phone: '', capacity: 12},
    {id: 15, bldg: '8173', room: '121b',   phone: '', capacity: 12},
    {id: 16, bldg: '8173', room: '121c',   phone: '', capacity: 12},
    {id: 17, bldg: '8173', room: '121d',   phone: '', capacity: 12},
    {id: 18, bldg: '8173', room: '123',    phone: '', capacity: 12},
    {id: 19, bldg: '8173', room: '124',    phone: '', capacity: 12},
    {id: 20, bldg: '8173', room: '125',    phone: '', capacity: 12},
    {id: 21, bldg: '8173', room: '127',    phone: '', capacity: 12},
    {id: 22, bldg: '8173', room: '128',    phone: '', capacity: 12},
    {id: 23, bldg: '8173', room: '129',    phone: '', capacity: 12},
    {id: 24, bldg: '8173', room: '130',    phone: '', capacity: 12},
    {id: 25, bldg: '8173', room: '131',    phone: '', capacity: 12},
    {id: 26, bldg: '8173', room: '137',    phone: '', capacity: 12},
    {id: 27, bldg: '8173', room: '138',    phone: '', capacity: 12},
    {id: 28, bldg: '8173', room: '140',    phone: '', capacity: 24},
    {id: 29, bldg: '8173', room: '141',    phone: '', capacity: 12},
    {id: 30, bldg: '8173', room: '142',    phone: '', capacity: 12},
    {id: 31, bldg: '8173', room: '143',    phone: '', capacity: 14},
    {id: 32, bldg: '8173', room: '144',    phone: '', capacity: 14},
    {id: 33, bldg: '8190', room: 'Blue',   phone: '', capacity: 12},
    {id: 34, bldg: '8190', room: 'Pink',   phone: '', capacity: 12} 
  ])
  await knex.raw('SELECT SETVAL(pg_get_serial_sequence(\'room\',\'id\'), (SELECT MAX(id) FROM room) )');

  await knex.schema.raw('TRUNCATE student CASCADE');
  await knex('student').del()
  await knex('student').insert([
    {id: 1, rank: 'spec', first: 'a', last: 'e_1_1', email: 's@sf.mil', phone_cell: ''},
    {id: 2, rank: 'spec', first: 'a', last: 'e_1_10', email: 's@sf.mil', phone_cell: ''},
    {id: 3, rank: 'spec', first: 'a', last: 'e_1_11', email: 's@sf.mil', phone_cell: ''},
    {id: 4, rank: 'spec', first: 'a', last: 'e_1_12', email: 's@sf.mil', phone_cell: ''},
    {id: 5, rank: 'spec', first: 'a', last: 'e_1_13', email: 's@sf.mil', phone_cell: ''},
    {id: 6, rank: 'spec', first: 'a', last: 'e_1_14', email: 's@sf.mil', phone_cell: ''},
    {id: 7, rank: 'spec', first: 'a', last: 'e_1_15', email: 's@sf.mil', phone_cell: ''},
    {id: 8, rank: 'spec', first: 'a', last: 'e_1_16', email: 's@sf.mil', phone_cell: ''},
    {id: 9, rank: 'spec', first: 'a', last: 'e_1_17', email: 's@sf.mil', phone_cell: ''},
    {id: 10, rank: 'spec', first: 'a', last: 'e_1_18', email: 's@sf.mil', phone_cell: ''},
    {id: 11, rank: 'spec', first: 'a', last: 'e_1_19', email: 's@sf.mil', phone_cell: ''},
    {id: 12, rank: 'spec', first: 'a', last: 'e_1_2', email: 's@sf.mil', phone_cell: ''},
    {id: 13, rank: 'spec', first: 'a', last: 'e_1_20', email: 's@sf.mil', phone_cell: ''},
    {id: 14, rank: 'spec', first: 'a', last: 'e_1_21', email: 's@sf.mil', phone_cell: ''},
    {id: 15, rank: 'spec', first: 'a', last: 'e_1_22', email: 's@sf.mil', phone_cell: ''},
    {id: 16, rank: 'spec', first: 'a', last: 'e_1_23', email: 's@sf.mil', phone_cell: ''},
    {id: 17, rank: 'spec', first: 'a', last: 'e_1_24', email: 's@sf.mil', phone_cell: ''},
    {id: 18, rank: 'spec', first: 'a', last: 'e_1_25', email: 's@sf.mil', phone_cell: ''},
    {id: 19, rank: 'spec', first: 'a', last: 'e_1_26', email: 's@sf.mil', phone_cell: ''},
    {id: 20, rank: 'spec', first: 'a', last: 'e_1_27', email: 's@sf.mil', phone_cell: ''},
    {id: 21, rank: 'spec', first: 'a', last: 'e_1_28', email: 's@sf.mil', phone_cell: ''},
    {id: 22, rank: 'spec', first: 'a', last: 'e_1_29', email: 's@sf.mil', phone_cell: ''},
    {id: 23, rank: 'spec', first: 'a', last: 'e_1_3', email: 's@sf.mil', phone_cell: ''},
    {id: 24, rank: 'spec', first: 'a', last: 'e_1_30', email: 's@sf.mil', phone_cell: ''},
    {id: 25, rank: 'spec', first: 'a', last: 'e_1_31', email: 's@sf.mil', phone_cell: ''},
    {id: 26, rank: 'spec', first: 'a', last: 'e_1_32', email: 's@sf.mil', phone_cell: ''},
    {id: 27, rank: 'spec', first: 'a', last: 'e_1_33', email: 's@sf.mil', phone_cell: ''},
    {id: 28, rank: 'spec', first: 'a', last: 'e_1_34', email: 's@sf.mil', phone_cell: ''},
    {id: 29, rank: 'spec', first: 'a', last: 'e_1_35', email: 's@sf.mil', phone_cell: ''},
    {id: 30, rank: 'spec', first: 'a', last: 'e_1_36', email: 's@sf.mil', phone_cell: ''},
    {id: 31, rank: 'spec', first: 'a', last: 'e_1_37', email: 's@sf.mil', phone_cell: ''},
    {id: 32, rank: 'spec', first: 'a', last: 'e_1_38', email: 's@sf.mil', phone_cell: ''},
    {id: 33, rank: 'spec', first: 'a', last: 'e_1_39', email: 's@sf.mil', phone_cell: ''},
    {id: 34, rank: 'spec', first: 'a', last: 'e_1_4', email: 's@sf.mil', phone_cell: ''},
    {id: 35, rank: 'spec', first: 'a', last: 'e_1_40', email: 's@sf.mil', phone_cell: ''},
    {id: 36, rank: 'spec', first: 'a', last: 'e_1_41', email: 's@sf.mil', phone_cell: ''},
    {id: 37, rank: 'spec', first: 'a', last: 'e_1_42', email: 's@sf.mil', phone_cell: ''},
    {id: 38, rank: 'spec', first: 'a', last: 'e_1_43', email: 's@sf.mil', phone_cell: ''},
    {id: 39, rank: 'spec', first: 'a', last: 'e_1_44', email: 's@sf.mil', phone_cell: ''},
    {id: 40, rank: 'spec', first: 'a', last: 'e_1_45', email: 's@sf.mil', phone_cell: ''},
    {id: 41, rank: 'spec', first: 'a', last: 'e_1_46', email: 's@sf.mil', phone_cell: ''},
    {id: 42, rank: 'spec', first: 'a', last: 'e_1_47', email: 's@sf.mil', phone_cell: ''},
    {id: 43, rank: 'spec', first: 'a', last: 'e_1_48', email: 's@sf.mil', phone_cell: ''},
    {id: 44, rank: 'spec', first: 'a', last: 'e_1_49', email: 's@sf.mil', phone_cell: ''},
    {id: 45, rank: 'spec', first: 'a', last: 'e_1_5', email: 's@sf.mil', phone_cell: ''},
    {id: 46, rank: 'spec', first: 'a', last: 'e_1_50', email: 's@sf.mil', phone_cell: ''},
    {id: 47, rank: 'spec', first: 'a', last: 'e_1_51', email: 's@sf.mil', phone_cell: ''},
    {id: 48, rank: 'spec', first: 'a', last: 'e_1_52', email: 's@sf.mil', phone_cell: ''},
    {id: 49, rank: 'spec', first: 'a', last: 'e_1_53', email: 's@sf.mil', phone_cell: ''},
    {id: 50, rank: 'spec', first: 'a', last: 'e_1_54', email: 's@sf.mil', phone_cell: ''},
    {id: 51, rank: 'spec', first: 'a', last: 'e_1_55', email: 's@sf.mil', phone_cell: ''},
    {id: 52, rank: 'spec', first: 'a', last: 'e_1_56', email: 's@sf.mil', phone_cell: ''},
    {id: 53, rank: 'spec', first: 'a', last: 'e_1_57', email: 's@sf.mil', phone_cell: ''},
    {id: 54, rank: 'spec', first: 'a', last: 'e_1_58', email: 's@sf.mil', phone_cell: ''},
    {id: 55, rank: 'spec', first: 'a', last: 'e_1_59', email: 's@sf.mil', phone_cell: ''},
    {id: 56, rank: 'spec', first: 'a', last: 'e_1_6', email: 's@sf.mil', phone_cell: ''},
    {id: 57, rank: 'spec', first: 'a', last: 'e_1_60', email: 's@sf.mil', phone_cell: ''},
    {id: 58, rank: 'spec', first: 'a', last: 'e_1_7', email: 's@sf.mil', phone_cell: ''},
    {id: 59, rank: 'spec', first: 'a', last: 'e_1_8', email: 's@sf.mil', phone_cell: ''},
    {id: 60, rank: 'spec', first: 'a', last: 'e_1_9', email: 's@sf.mil', phone_cell: ''},
    {id: 61, rank: 'spec', first: 'a', last: 'e_2_1', email: 's@sf.mil', phone_cell: ''},
    {id: 62, rank: 'spec', first: 'a', last: 'e_2_10', email: 's@sf.mil', phone_cell: ''},
    {id: 63, rank: 'spec', first: 'a', last: 'e_2_11', email: 's@sf.mil', phone_cell: ''},
    {id: 64, rank: 'spec', first: 'a', last: 'e_2_12', email: 's@sf.mil', phone_cell: ''},
    {id: 65, rank: 'spec', first: 'a', last: 'e_2_13', email: 's@sf.mil', phone_cell: ''},
    {id: 66, rank: 'spec', first: 'a', last: 'e_2_14', email: 's@sf.mil', phone_cell: ''},
    {id: 67, rank: 'spec', first: 'a', last: 'e_2_15', email: 's@sf.mil', phone_cell: ''},
    {id: 68, rank: 'spec', first: 'a', last: 'e_2_16', email: 's@sf.mil', phone_cell: ''},
    {id: 69, rank: 'spec', first: 'a', last: 'e_2_17', email: 's@sf.mil', phone_cell: ''},
    {id: 70, rank: 'spec', first: 'a', last: 'e_2_18', email: 's@sf.mil', phone_cell: ''},
    {id: 71, rank: 'spec', first: 'a', last: 'e_2_19', email: 's@sf.mil', phone_cell: ''},
    {id: 72, rank: 'spec', first: 'a', last: 'e_2_2', email: 's@sf.mil', phone_cell: ''},
    {id: 73, rank: 'spec', first: 'a', last: 'e_2_20', email: 's@sf.mil', phone_cell: ''},
    {id: 74, rank: 'spec', first: 'a', last: 'e_2_21', email: 's@sf.mil', phone_cell: ''},
    {id: 75, rank: 'spec', first: 'a', last: 'e_2_22', email: 's@sf.mil', phone_cell: ''},
    {id: 76, rank: 'spec', first: 'a', last: 'e_2_23', email: 's@sf.mil', phone_cell: ''},
    {id: 77, rank: 'spec', first: 'a', last: 'e_2_24', email: 's@sf.mil', phone_cell: ''},
    {id: 78, rank: 'spec', first: 'a', last: 'e_2_25', email: 's@sf.mil', phone_cell: ''},
    {id: 79, rank: 'spec', first: 'a', last: 'e_2_26', email: 's@sf.mil', phone_cell: ''},
    {id: 80, rank: 'spec', first: 'a', last: 'e_2_27', email: 's@sf.mil', phone_cell: ''},
    {id: 81, rank: 'spec', first: 'a', last: 'e_2_28', email: 's@sf.mil', phone_cell: ''},
    {id: 82, rank: 'spec', first: 'a', last: 'e_2_29', email: 's@sf.mil', phone_cell: ''},
    {id: 83, rank: 'spec', first: 'a', last: 'e_2_3', email: 's@sf.mil', phone_cell: ''},
    {id: 84, rank: 'spec', first: 'a', last: 'e_2_30', email: 's@sf.mil', phone_cell: ''},
    {id: 85, rank: 'spec', first: 'a', last: 'e_2_31', email: 's@sf.mil', phone_cell: ''},
    {id: 86, rank: 'spec', first: 'a', last: 'e_2_32', email: 's@sf.mil', phone_cell: ''},
    {id: 87, rank: 'spec', first: 'a', last: 'e_2_33', email: 's@sf.mil', phone_cell: ''},
    {id: 88, rank: 'spec', first: 'a', last: 'e_2_34', email: 's@sf.mil', phone_cell: ''},
    {id: 89, rank: 'spec', first: 'a', last: 'e_2_35', email: 's@sf.mil', phone_cell: ''},
    {id: 90, rank: 'spec', first: 'a', last: 'e_2_36', email: 's@sf.mil', phone_cell: ''},
    {id: 91, rank: 'spec', first: 'a', last: 'e_2_37', email: 's@sf.mil', phone_cell: ''},
    {id: 92, rank: 'spec', first: 'a', last: 'e_2_38', email: 's@sf.mil', phone_cell: ''},
    {id: 93, rank: 'spec', first: 'a', last: 'e_2_39', email: 's@sf.mil', phone_cell: ''},
    {id: 94, rank: 'spec', first: 'a', last: 'e_2_4', email: 's@sf.mil', phone_cell: ''},
    {id: 95, rank: 'spec', first: 'a', last: 'e_2_40', email: 's@sf.mil', phone_cell: ''},
    {id: 96, rank: 'spec', first: 'a', last: 'e_2_41', email: 's@sf.mil', phone_cell: ''},
    {id: 97, rank: 'spec', first: 'a', last: 'e_2_42', email: 's@sf.mil', phone_cell: ''},
    {id: 98, rank: 'spec', first: 'a', last: 'e_2_43', email: 's@sf.mil', phone_cell: ''},
    {id: 99, rank: 'spec', first: 'a', last: 'e_2_44', email: 's@sf.mil', phone_cell: ''},
    {id: 100, rank: 'spec', first: 'a', last: 'e_2_45', email: 's@sf.mil', phone_cell: ''},
    {id: 101, rank: 'spec', first: 'a', last: 'e_2_46', email: 's@sf.mil', phone_cell: ''},
    {id: 102, rank: 'spec', first: 'a', last: 'e_2_47', email: 's@sf.mil', phone_cell: ''},
    {id: 103, rank: 'spec', first: 'a', last: 'e_2_48', email: 's@sf.mil', phone_cell: ''},
    {id: 104, rank: 'spec', first: 'a', last: 'e_2_49', email: 's@sf.mil', phone_cell: ''},
    {id: 105, rank: 'spec', first: 'a', last: 'e_2_5', email: 's@sf.mil', phone_cell: ''},
    {id: 106, rank: 'spec', first: 'a', last: 'e_2_50', email: 's@sf.mil', phone_cell: ''},
    {id: 107, rank: 'spec', first: 'a', last: 'e_2_51', email: 's@sf.mil', phone_cell: ''},
    {id: 108, rank: 'spec', first: 'a', last: 'e_2_52', email: 's@sf.mil', phone_cell: ''},
    {id: 109, rank: 'spec', first: 'a', last: 'e_2_53', email: 's@sf.mil', phone_cell: ''},
    {id: 110, rank: 'spec', first: 'a', last: 'e_2_54', email: 's@sf.mil', phone_cell: ''},
    {id: 111, rank: 'spec', first: 'a', last: 'e_2_55', email: 's@sf.mil', phone_cell: ''},
    {id: 112, rank: 'spec', first: 'a', last: 'e_2_56', email: 's@sf.mil', phone_cell: ''},
    {id: 113, rank: 'spec', first: 'a', last: 'e_2_57', email: 's@sf.mil', phone_cell: ''},
    {id: 114, rank: 'spec', first: 'a', last: 'e_2_58', email: 's@sf.mil', phone_cell: ''},
    {id: 115, rank: 'spec', first: 'a', last: 'e_2_59', email: 's@sf.mil', phone_cell: ''},
    {id: 116, rank: 'spec', first: 'a', last: 'e_2_6', email: 's@sf.mil', phone_cell: ''},
    {id: 117, rank: 'spec', first: 'a', last: 'e_2_60', email: 's@sf.mil', phone_cell: ''},
    {id: 118, rank: 'spec', first: 'a', last: 'e_2_7', email: 's@sf.mil', phone_cell: ''},
    {id: 119, rank: 'spec', first: 'a', last: 'e_2_8', email: 's@sf.mil', phone_cell: ''},
    {id: 120, rank: 'spec', first: 'a', last: 'e_2_9', email: 's@sf.mil', phone_cell: ''},
    {id: 121, rank: 'capt', first: 'a', last: 'o_1_1', email: 's@sf.mil', phone_cell: ''},
    {id: 122, rank: 'capt', first: 'a', last: 'o_1_10', email: 's@sf.mil', phone_cell: ''},
    {id: 123, rank: 'capt', first: 'a', last: 'o_1_11', email: 's@sf.mil', phone_cell: ''},
    {id: 124, rank: 'capt', first: 'a', last: 'o_1_12', email: 's@sf.mil', phone_cell: ''},
    {id: 125, rank: 'capt', first: 'a', last: 'o_1_13', email: 's@sf.mil', phone_cell: ''},
    {id: 126, rank: 'capt', first: 'a', last: 'o_1_14', email: 's@sf.mil', phone_cell: ''},
    {id: 127, rank: 'capt', first: 'a', last: 'o_1_15', email: 's@sf.mil', phone_cell: ''},
    {id: 128, rank: 'capt', first: 'a', last: 'o_1_16', email: 's@sf.mil', phone_cell: ''},
    {id: 129, rank: 'capt', first: 'a', last: 'o_1_17', email: 's@sf.mil', phone_cell: ''},
    {id: 130, rank: 'capt', first: 'a', last: 'o_1_18', email: 's@sf.mil', phone_cell: ''},
    {id: 131, rank: 'capt', first: 'a', last: 'o_1_19', email: 's@sf.mil', phone_cell: ''},
    {id: 132, rank: 'capt', first: 'a', last: 'o_1_2', email: 's@sf.mil', phone_cell: ''},
    {id: 133, rank: 'capt', first: 'a', last: 'o_1_20', email: 's@sf.mil', phone_cell: ''},
    {id: 134, rank: 'capt', first: 'a', last: 'o_1_21', email: 's@sf.mil', phone_cell: ''},
    {id: 135, rank: 'capt', first: 'a', last: 'o_1_22', email: 's@sf.mil', phone_cell: ''},
    {id: 136, rank: 'capt', first: 'a', last: 'o_1_23', email: 's@sf.mil', phone_cell: ''},
    {id: 137, rank: 'capt', first: 'a', last: 'o_1_24', email: 's@sf.mil', phone_cell: ''},
    {id: 138, rank: 'capt', first: 'a', last: 'o_1_25', email: 's@sf.mil', phone_cell: ''},
    {id: 139, rank: 'capt', first: 'a', last: 'o_1_26', email: 's@sf.mil', phone_cell: ''},
    {id: 140, rank: 'capt', first: 'a', last: 'o_1_27', email: 's@sf.mil', phone_cell: ''},
    {id: 141, rank: 'capt', first: 'a', last: 'o_1_28', email: 's@sf.mil', phone_cell: ''},
    {id: 142, rank: 'capt', first: 'a', last: 'o_1_29', email: 's@sf.mil', phone_cell: ''},
    {id: 143, rank: 'capt', first: 'a', last: 'o_1_3', email: 's@sf.mil', phone_cell: ''},
    {id: 144, rank: 'capt', first: 'a', last: 'o_1_30', email: 's@sf.mil', phone_cell: ''},
    {id: 145, rank: 'capt', first: 'a', last: 'o_1_31', email: 's@sf.mil', phone_cell: ''},
    {id: 146, rank: 'capt', first: 'a', last: 'o_1_32', email: 's@sf.mil', phone_cell: ''},
    {id: 147, rank: 'capt', first: 'a', last: 'o_1_33', email: 's@sf.mil', phone_cell: ''},
    {id: 148, rank: 'capt', first: 'a', last: 'o_1_34', email: 's@sf.mil', phone_cell: ''},
    {id: 149, rank: 'capt', first: 'a', last: 'o_1_35', email: 's@sf.mil', phone_cell: ''},
    {id: 150, rank: 'capt', first: 'a', last: 'o_1_36', email: 's@sf.mil', phone_cell: ''},
    {id: 151, rank: 'capt', first: 'a', last: 'o_1_37', email: 's@sf.mil', phone_cell: ''},
    {id: 152, rank: 'capt', first: 'a', last: 'o_1_38', email: 's@sf.mil', phone_cell: ''},
    {id: 153, rank: 'capt', first: 'a', last: 'o_1_39', email: 's@sf.mil', phone_cell: ''},
    {id: 154, rank: 'capt', first: 'a', last: 'o_1_4', email: 's@sf.mil', phone_cell: ''},
    {id: 155, rank: 'capt', first: 'a', last: 'o_1_40', email: 's@sf.mil', phone_cell: ''},
    {id: 156, rank: 'capt', first: 'a', last: 'o_1_41', email: 's@sf.mil', phone_cell: ''},
    {id: 157, rank: 'capt', first: 'a', last: 'o_1_42', email: 's@sf.mil', phone_cell: ''},
    {id: 158, rank: 'capt', first: 'a', last: 'o_1_43', email: 's@sf.mil', phone_cell: ''},
    {id: 159, rank: 'capt', first: 'a', last: 'o_1_44', email: 's@sf.mil', phone_cell: ''},
    {id: 160, rank: 'capt', first: 'a', last: 'o_1_45', email: 's@sf.mil', phone_cell: ''},
    {id: 161, rank: 'capt', first: 'a', last: 'o_1_46', email: 's@sf.mil', phone_cell: ''},
    {id: 162, rank: 'capt', first: 'a', last: 'o_1_47', email: 's@sf.mil', phone_cell: ''},
    {id: 163, rank: 'capt', first: 'a', last: 'o_1_48', email: 's@sf.mil', phone_cell: ''},
    {id: 164, rank: 'capt', first: 'a', last: 'o_1_5', email: 's@sf.mil', phone_cell: ''},
    {id: 165, rank: 'capt', first: 'a', last: 'o_1_6', email: 's@sf.mil', phone_cell: ''},
    {id: 166, rank: 'capt', first: 'a', last: 'o_1_7', email: 's@sf.mil', phone_cell: ''},
    {id: 167, rank: 'capt', first: 'a', last: 'o_1_8', email: 's@sf.mil', phone_cell: ''},
    {id: 168, rank: 'capt', first: 'a', last: 'o_1_9', email: 's@sf.mil', phone_cell: ''},
    {id: 169, rank: 'capt', first: 'a', last: 'o_2_1', email: 's@sf.mil', phone_cell: ''},
    {id: 170, rank: 'capt', first: 'a', last: 'o_2_10', email: 's@sf.mil', phone_cell: ''},
    {id: 171, rank: 'capt', first: 'a', last: 'o_2_11', email: 's@sf.mil', phone_cell: ''},
    {id: 172, rank: 'capt', first: 'a', last: 'o_2_12', email: 's@sf.mil', phone_cell: ''},
    {id: 173, rank: 'capt', first: 'a', last: 'o_2_13', email: 's@sf.mil', phone_cell: ''},
    {id: 174, rank: 'capt', first: 'a', last: 'o_2_14', email: 's@sf.mil', phone_cell: ''},
    {id: 175, rank: 'capt', first: 'a', last: 'o_2_15', email: 's@sf.mil', phone_cell: ''},
    {id: 176, rank: 'capt', first: 'a', last: 'o_2_16', email: 's@sf.mil', phone_cell: ''},
    {id: 177, rank: 'capt', first: 'a', last: 'o_2_17', email: 's@sf.mil', phone_cell: ''},
    {id: 178, rank: 'capt', first: 'a', last: 'o_2_18', email: 's@sf.mil', phone_cell: ''},
    {id: 179, rank: 'capt', first: 'a', last: 'o_2_19', email: 's@sf.mil', phone_cell: ''},
    {id: 180, rank: 'capt', first: 'a', last: 'o_2_2', email: 's@sf.mil', phone_cell: ''},
    {id: 181, rank: 'capt', first: 'a', last: 'o_2_20', email: 's@sf.mil', phone_cell: ''},
    {id: 182, rank: 'capt', first: 'a', last: 'o_2_21', email: 's@sf.mil', phone_cell: ''},
    {id: 183, rank: 'capt', first: 'a', last: 'o_2_22', email: 's@sf.mil', phone_cell: ''},
    {id: 184, rank: 'capt', first: 'a', last: 'o_2_23', email: 's@sf.mil', phone_cell: ''},
    {id: 185, rank: 'capt', first: 'a', last: 'o_2_24', email: 's@sf.mil', phone_cell: ''},
    {id: 186, rank: 'capt', first: 'a', last: 'o_2_25', email: 's@sf.mil', phone_cell: ''},
    {id: 187, rank: 'capt', first: 'a', last: 'o_2_26', email: 's@sf.mil', phone_cell: ''},
    {id: 188, rank: 'capt', first: 'a', last: 'o_2_27', email: 's@sf.mil', phone_cell: ''},
    {id: 189, rank: 'capt', first: 'a', last: 'o_2_28', email: 's@sf.mil', phone_cell: ''},
    {id: 190, rank: 'capt', first: 'a', last: 'o_2_29', email: 's@sf.mil', phone_cell: ''},
    {id: 191, rank: 'capt', first: 'a', last: 'o_2_3', email: 's@sf.mil', phone_cell: ''},
    {id: 192, rank: 'capt', first: 'a', last: 'o_2_30', email: 's@sf.mil', phone_cell: ''},
    {id: 193, rank: 'capt', first: 'a', last: 'o_2_31', email: 's@sf.mil', phone_cell: ''},
    {id: 194, rank: 'capt', first: 'a', last: 'o_2_32', email: 's@sf.mil', phone_cell: ''},
    {id: 195, rank: 'capt', first: 'a', last: 'o_2_33', email: 's@sf.mil', phone_cell: ''},
    {id: 196, rank: 'capt', first: 'a', last: 'o_2_34', email: 's@sf.mil', phone_cell: ''},
    {id: 197, rank: 'capt', first: 'a', last: 'o_2_35', email: 's@sf.mil', phone_cell: ''},
    {id: 198, rank: 'capt', first: 'a', last: 'o_2_36', email: 's@sf.mil', phone_cell: ''},
    {id: 199, rank: 'capt', first: 'a', last: 'o_2_37', email: 's@sf.mil', phone_cell: ''},
    {id: 200, rank: 'capt', first: 'a', last: 'o_2_38', email: 's@sf.mil', phone_cell: ''},
    {id: 201, rank: 'capt', first: 'a', last: 'o_2_39', email: 's@sf.mil', phone_cell: ''},
    {id: 202, rank: 'capt', first: 'a', last: 'o_2_4', email: 's@sf.mil', phone_cell: ''},
    {id: 203, rank: 'capt', first: 'a', last: 'o_2_40', email: 's@sf.mil', phone_cell: ''},
    {id: 204, rank: 'capt', first: 'a', last: 'o_2_41', email: 's@sf.mil', phone_cell: ''},
    {id: 205, rank: 'capt', first: 'a', last: 'o_2_42', email: 's@sf.mil', phone_cell: ''},
    {id: 206, rank: 'capt', first: 'a', last: 'o_2_43', email: 's@sf.mil', phone_cell: ''},
    {id: 207, rank: 'capt', first: 'a', last: 'o_2_44', email: 's@sf.mil', phone_cell: ''},
    {id: 208, rank: 'capt', first: 'a', last: 'o_2_45', email: 's@sf.mil', phone_cell: ''},
    {id: 209, rank: 'capt', first: 'a', last: 'o_2_46', email: 's@sf.mil', phone_cell: ''},
    {id: 210, rank: 'capt', first: 'a', last: 'o_2_47', email: 's@sf.mil', phone_cell: ''},
    {id: 211, rank: 'capt', first: 'a', last: 'o_2_48', email: 's@sf.mil', phone_cell: ''},
    {id: 212, rank: 'capt', first: 'a', last: 'o_2_5', email: 's@sf.mil', phone_cell: ''},
    {id: 213, rank: 'capt', first: 'a', last: 'o_2_6', email: 's@sf.mil', phone_cell: ''},
    {id: 214, rank: 'capt', first: 'a', last: 'o_2_7', email: 's@sf.mil', phone_cell: ''},
    {id: 215, rank: 'capt', first: 'a', last: 'o_2_8', email: 's@sf.mil', phone_cell: ''},
    {id: 216, rank: 'capt', first: 'a', last: 'o_2_9', email: 's@sf.mil', phone_cell: ''},
    {id: 217, rank: 'capt', first: 'a', last: 'o_3_1', email: 's@sf.mil', phone_cell: ''},
    {id: 218, rank: 'capt', first: 'a', last: 'o_3_10', email: 's@sf.mil', phone_cell: ''},
    {id: 219, rank: 'capt', first: 'a', last: 'o_3_11', email: 's@sf.mil', phone_cell: ''},
    {id: 220, rank: 'capt', first: 'a', last: 'o_3_12', email: 's@sf.mil', phone_cell: ''},
    {id: 221, rank: 'capt', first: 'a', last: 'o_3_13', email: 's@sf.mil', phone_cell: ''},
    {id: 222, rank: 'capt', first: 'a', last: 'o_3_14', email: 's@sf.mil', phone_cell: ''},
    {id: 223, rank: 'capt', first: 'a', last: 'o_3_15', email: 's@sf.mil', phone_cell: ''},
    {id: 224, rank: 'capt', first: 'a', last: 'o_3_16', email: 's@sf.mil', phone_cell: ''},
    {id: 225, rank: 'capt', first: 'a', last: 'o_3_17', email: 's@sf.mil', phone_cell: ''},
    {id: 226, rank: 'capt', first: 'a', last: 'o_3_18', email: 's@sf.mil', phone_cell: ''},
    {id: 227, rank: 'capt', first: 'a', last: 'o_3_19', email: 's@sf.mil', phone_cell: ''},
    {id: 228, rank: 'capt', first: 'a', last: 'o_3_2', email: 's@sf.mil', phone_cell: ''},
    {id: 229, rank: 'capt', first: 'a', last: 'o_3_20', email: 's@sf.mil', phone_cell: ''},
    {id: 230, rank: 'capt', first: 'a', last: 'o_3_21', email: 's@sf.mil', phone_cell: ''},
    {id: 231, rank: 'capt', first: 'a', last: 'o_3_22', email: 's@sf.mil', phone_cell: ''},
    {id: 232, rank: 'capt', first: 'a', last: 'o_3_23', email: 's@sf.mil', phone_cell: ''},
    {id: 233, rank: 'capt', first: 'a', last: 'o_3_24', email: 's@sf.mil', phone_cell: ''},
    {id: 234, rank: 'capt', first: 'a', last: 'o_3_25', email: 's@sf.mil', phone_cell: ''},
    {id: 235, rank: 'capt', first: 'a', last: 'o_3_26', email: 's@sf.mil', phone_cell: ''},
    {id: 236, rank: 'capt', first: 'a', last: 'o_3_27', email: 's@sf.mil', phone_cell: ''},
    {id: 237, rank: 'capt', first: 'a', last: 'o_3_28', email: 's@sf.mil', phone_cell: ''},
    {id: 238, rank: 'capt', first: 'a', last: 'o_3_29', email: 's@sf.mil', phone_cell: ''},
    {id: 239, rank: 'capt', first: 'a', last: 'o_3_3', email: 's@sf.mil', phone_cell: ''},
    {id: 240, rank: 'capt', first: 'a', last: 'o_3_30', email: 's@sf.mil', phone_cell: ''},
    {id: 241, rank: 'capt', first: 'a', last: 'o_3_31', email: 's@sf.mil', phone_cell: ''},
    {id: 242, rank: 'capt', first: 'a', last: 'o_3_32', email: 's@sf.mil', phone_cell: ''},
    {id: 243, rank: 'capt', first: 'a', last: 'o_3_33', email: 's@sf.mil', phone_cell: ''},
    {id: 244, rank: 'capt', first: 'a', last: 'o_3_34', email: 's@sf.mil', phone_cell: ''},
    {id: 245, rank: 'capt', first: 'a', last: 'o_3_35', email: 's@sf.mil', phone_cell: ''},
    {id: 246, rank: 'capt', first: 'a', last: 'o_3_36', email: 's@sf.mil', phone_cell: ''},
    {id: 247, rank: 'capt', first: 'a', last: 'o_3_37', email: 's@sf.mil', phone_cell: ''},
    {id: 248, rank: 'capt', first: 'a', last: 'o_3_38', email: 's@sf.mil', phone_cell: ''},
    {id: 249, rank: 'capt', first: 'a', last: 'o_3_39', email: 's@sf.mil', phone_cell: ''},
    {id: 250, rank: 'capt', first: 'a', last: 'o_3_4', email: 's@sf.mil', phone_cell: ''},
    {id: 251, rank: 'capt', first: 'a', last: 'o_3_40', email: 's@sf.mil', phone_cell: ''},
    {id: 252, rank: 'capt', first: 'a', last: 'o_3_41', email: 's@sf.mil', phone_cell: ''},
    {id: 253, rank: 'capt', first: 'a', last: 'o_3_42', email: 's@sf.mil', phone_cell: ''},
    {id: 254, rank: 'capt', first: 'a', last: 'o_3_43', email: 's@sf.mil', phone_cell: ''},
    {id: 255, rank: 'capt', first: 'a', last: 'o_3_44', email: 's@sf.mil', phone_cell: ''},
    {id: 256, rank: 'capt', first: 'a', last: 'o_3_45', email: 's@sf.mil', phone_cell: ''},
    {id: 257, rank: 'capt', first: 'a', last: 'o_3_46', email: 's@sf.mil', phone_cell: ''},
    {id: 258, rank: 'capt', first: 'a', last: 'o_3_47', email: 's@sf.mil', phone_cell: ''},
    {id: 259, rank: 'capt', first: 'a', last: 'o_3_48', email: 's@sf.mil', phone_cell: ''},
    {id: 260, rank: 'capt', first: 'a', last: 'o_3_49', email: 's@sf.mil', phone_cell: ''},
    {id: 261, rank: 'capt', first: 'a', last: 'o_3_5', email: 's@sf.mil', phone_cell: ''},
    {id: 262, rank: 'capt', first: 'a', last: 'o_3_50', email: 's@sf.mil', phone_cell: ''},
    {id: 263, rank: 'capt', first: 'a', last: 'o_3_51', email: 's@sf.mil', phone_cell: ''},
    {id: 264, rank: 'capt', first: 'a', last: 'o_3_52', email: 's@sf.mil', phone_cell: ''},
    {id: 265, rank: 'capt', first: 'a', last: 'o_3_53', email: 's@sf.mil', phone_cell: ''},
    {id: 266, rank: 'capt', first: 'a', last: 'o_3_54', email: 's@sf.mil', phone_cell: ''},
    {id: 267, rank: 'capt', first: 'a', last: 'o_3_55', email: 's@sf.mil', phone_cell: ''},
    {id: 268, rank: 'capt', first: 'a', last: 'o_3_56', email: 's@sf.mil', phone_cell: ''},
    {id: 269, rank: 'capt', first: 'a', last: 'o_3_57', email: 's@sf.mil', phone_cell: ''},
    {id: 270, rank: 'capt', first: 'a', last: 'o_3_58', email: 's@sf.mil', phone_cell: ''},
    {id: 271, rank: 'capt', first: 'a', last: 'o_3_59', email: 's@sf.mil', phone_cell: ''},
    {id: 272, rank: 'capt', first: 'a', last: 'o_3_6', email: 's@sf.mil', phone_cell: ''},
    {id: 273, rank: 'capt', first: 'a', last: 'o_3_60', email: 's@sf.mil', phone_cell: ''},
    {id: 274, rank: 'capt', first: 'a', last: 'o_3_61', email: 's@sf.mil', phone_cell: ''},
    {id: 275, rank: 'capt', first: 'a', last: 'o_3_62', email: 's@sf.mil', phone_cell: ''},
    {id: 276, rank: 'capt', first: 'a', last: 'o_3_63', email: 's@sf.mil', phone_cell: ''},
    {id: 277, rank: 'capt', first: 'a', last: 'o_3_64', email: 's@sf.mil', phone_cell: ''},
    {id: 278, rank: 'capt', first: 'a', last: 'o_3_65', email: 's@sf.mil', phone_cell: ''},
    {id: 279, rank: 'capt', first: 'a', last: 'o_3_66', email: 's@sf.mil', phone_cell: ''},
    {id: 280, rank: 'capt', first: 'a', last: 'o_3_67', email: 's@sf.mil', phone_cell: ''},
    {id: 281, rank: 'capt', first: 'a', last: 'o_3_68', email: 's@sf.mil', phone_cell: ''},
    {id: 282, rank: 'capt', first: 'a', last: 'o_3_69', email: 's@sf.mil', phone_cell: ''},
    {id: 283, rank: 'capt', first: 'a', last: 'o_3_7', email: 's@sf.mil', phone_cell: ''},
    {id: 284, rank: 'capt', first: 'a', last: 'o_3_70', email: 's@sf.mil', phone_cell: ''},
    {id: 285, rank: 'capt', first: 'a', last: 'o_3_71', email: 's@sf.mil', phone_cell: ''},
    {id: 286, rank: 'capt', first: 'a', last: 'o_3_72', email: 's@sf.mil', phone_cell: ''},
    {id: 287, rank: 'capt', first: 'a', last: 'o_3_8', email: 's@sf.mil', phone_cell: ''},
    {id: 288, rank: 'capt', first: 'a', last: 'o_3_9', email: 's@sf.mil', phone_cell: ''}
  ]);

  await knex.raw('SELECT SETVAL(pg_get_serial_sequence(\'student\',\'id\'), (SELECT MAX(id) FROM student) )');

  await knex.schema.raw('TRUNCATE class CASCADE');
  await knex('class').del()
  await knex('class').insert([
    {id: 1,  dept: 'OEM', number: '101'},
    {id: 2,  dept: 'OEM', number: '201'},
    {id: 3,  dept: 'SBM', number: '101'},
    {id: 4,  dept: 'SBM', number: '201'},
    {id: 5,  dept: 'SEW', number: '101'},
    {id: 6,  dept: 'SEW', number: '201'},
    {id: 7,  dept: 'FUN', number: '101'},
    {id: 8,  dept: 'FUN', number: '201'},
    {id: 9,  dept: 'INT', number: '101'},
    {id: 10,  dept: 'INT', number: '102'},
    {id: 11,  dept: 'INT', number: '103'},
    {id: 12,  dept: 'INT', number: '104'}
  ]);

  await knex.raw('SELECT SETVAL(pg_get_serial_sequence(\'class\',\'id\'), (SELECT MAX(id) FROM class) )');

  await knex.schema.raw('TRUNCATE shift CASCADE ');
  await knex('shift').del()
  await knex('shift').insert([
    {id: 1,  day: 'MW', start: '07:30:00', end: '11:30:00'},
    {id: 2,  day: 'MW', start: '12:30:00', end: '16:30:00'},
    {id: 3,  day: 'TT', start: '07:30:00', end: '11:30:00'},
    {id: 4,  day: 'TT', start: '12:30:00', end: '16:30:00'}
  ]);

  await knex.schema.raw('TRUNCATE semester CASCADE');
  await knex('semester').del()
  await knex('semester').insert([
    {id: 1, start: '06/06/22', end: '07/22/22'}
  ]);
};
